name: 'Test Github Action'
description: 'A Github Action used for testing various core functionalities'
inputs:
  test-input:
    description: 'An input for testing'
    required: true
    default: 'Test Input!'
outputs:
  test-output:
    description: 'A test output'
runs:
  using: 'node20'
  main: 'index.js'