name: core
description: >-
  The github actions core package rewritten in dart
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies:
  http: ^1.1.2
  meta: ^1.11.0
  
dev_dependencies:
  build_runner: ^2.4.8
  mockito: ^5.4.4
  test: '>=1.15.0 <2.0.0'