name: Dart Github Action Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-action:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: dart pub get
        run: dart pub get
      - name: Test local action
        uses: ./
        with:
          test-input: "This is my test input"
          test-input-boolean: TRUE
          test-input-multiline: |
            This
            is
            my
            multiline
            input
