name: Integration Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  integration_test_input:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core/test/integration/input
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: dart pub get
        run: dart pub get
      - name: 'Integration test: input'
        uses: ./core/test/integration/input
  integration_test_logging:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core/test/integration/logging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: dart pub get
        run: dart pub get
      - name: 'Integration test: logging'
        uses: ./core/test/integration/logging
  integration_test_export:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core/test/integration/export
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: dart pub get
        run: dart pub get
      - name: 'Integration test: export'
        uses: ./core/test/integration/export
  integration_test_output:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core/test/integration/output
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: dart pub get
        run: dart pub get
      - name: 'Integration test: output'
        uses: ./core/test/integration/output
